"""AI provider base interfaces and provider registry.

This module defines the ProviderRegistry used to register and resolve AI providers by
name and the BaseAIProvider abstract class which provider implementations should
inherit from. Providers must implement async streaming via `stream_chat` and
a simple non-streaming `chat` method.

Design goals:
- Keep provider implementations decoupled from core. Providers are registered
  in the ProviderRegistry and consumers request providers by name.
- Providers must not hardcode keys; clients should configure providers via environment
  variables and pass credentials during provider construction.
"""
from __future__ import annotations

import asyncio
from typing import AsyncIterator, Callable, Dict, Optional, Sequence

from jarvis.core.ports import IAIProvider
from jarvis.utils.logger import get_logger


class ProviderRegistry:
    """Registry to register and resolve AI providers by name.

    Providers are registered as callables (factories) that return an IAIProvider
    instance. This allows lazy instantiation and provider-specific configuration.
    """

    def __init__(self) -> None:
        self._providers: Dict[str, Callable[[], IAIProvider]] = {}
        self._logger = get_logger(__name__)

    def register(self, name: str, factory: Callable[[], IAIProvider]) -> None:
        if name in self._providers:
            self._logger.warning("Overwriting existing AI provider registration", provider=name)
        self._providers[name] = factory
        self._logger.debug("AI provider registered", provider=name)

    def available(self) -> list[str]:
        return list(self._providers.keys())

    def get(self, name: str) -> IAIProvider:
        if name not in self._providers:
            raise KeyError(f"AI provider '{name}' is not registered")
        return self._providers[name]()


class BaseAIProvider(IAIProvider):
    """Base class for AI providers offering helpers for streaming and retries.

    Concrete providers must implement the `_astream_chat` coroutine which yields
    text segments as they are generated by a remote provider or a local model.
    """

    def __init__(self, name: str, default_model: Optional[str] = None) -> None:
        self.name = name
        self.default_model = default_model
        self._logger = get_logger(f"jarvis.ai.providers.{name}")

    async def stream_chat(self, prompt: str, context: Sequence[str] | None = None) -> AsyncIterator[str]:
        """Default streaming wrapper that yields segments from `_astream_chat`.

        Providers should implement `_astream_chat`.
        """
        async for chunk in self._astream_chat(prompt, context or []):
            yield chunk

    async def chat(self, prompt: str, context: Sequence[str] | None = None) -> str:
        """Convenience method to collect a full response from the streaming API."""
        parts = []
        async for p in self.stream_chat(prompt, context):
            parts.append(p)
        return "".join(parts)

    async def _astream_chat(self, prompt: str, context: Sequence[str]) -> AsyncIterator[str]:
        """Providers must override this to stream text chunks.

        Simple default implementation yields the prompt immediately (for testing).
        """
        yield prompt
